### ISSUE TITLE
Build and Run Snipes on MacOs: SDL_CreateWindow: NSWindow drag regions should only be invalidated on the Main Thread!

### ISSUE THREAD

**Issue by chrisfcarroll** [Davidebyzero/Snipes#13] opened 2020-06-29 11:56 UTC
I can build after installing 
* SDL2 from the dmg installer at https://www.libsdl.org/download-2.0.php
* SDL2_ttf from the dmg installer at https://www.libsdl.org/projects/SDL_ttf

I can run after copying `SnipesConsole.ttf` into the project directory (forgetting the font file => segmentation fault)

But running it just gets me 

```
SDL_CreateWindow: NSWindow drag regions should only be invalidated on the Main Thread!
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894.50.103/AppKit.subproj/NSView.m, line 13568.
zsh: illegal hardware instruction  Snipes/snipes
```
with
```
Crashed Thread:        1  ConsoleThread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [67558]
```

And alas, I'm a C++ newbie.

**Comment by chrisfcarroll** [comment] 2020-06-29 13:51
Probably a kind of duplicate of #8

**Comment by CyberShadow** [comment] 2024-04-14 12:15
Yes, thanks; let's continue there.

**Comment by CyberShadow** [comment] 2024-04-14 12:16
Duplicate of #8

**Closed by CyberShadow** 2024-04-14 12:15 UTC
