### ISSUE TITLE
compiled on Mac -- no window shows

### ISSUE THREAD

**Issue by bblais** [Davidebyzero/Snipes#18] opened 2024-05-14 01:12 UTC
I've compiled snipes on the Mac, installing the SDL dependencies using home-brew.  I get this printed out: "SDL_CreateWindow: NSWindow should only be instantiated on the main thread!" and an exec window icon shows up in the dock (so something is running) but no other window shows.  Has anyone gotten snipes working on a Mac?

**Comment by CyberShadow** [comment] 2024-05-14 05:09
It compiles by accident, and is known to not work. See https://github.com/Davidebyzero/Snipes/issues/8#issuecomment-2054031054  -  maybe you can help us fix it?

Duplicate of #8

**Closed as not planned by CyberShadow** 2024-05-14 05:09 UTC
